org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
org.gradle.configuration-cache=false
org.gradle.caching=true

# Mod Properties
mod_version=1.1.0
maven_group=dev.gxlg.autoenchanter
archives_base_name=auto-enchanter

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.2
loader_version=0.19.3
loom_version=1.17-SNAPSHOT

# Dependencies
fabric_api_version=0.154.2+26.2
