name: Build

on:
  push:
    branches: [ "**" ]
    paths:
      - "src/**"
      - "gradle.properties"
      - "build.gradle"
      - "gradle/**"
      - ".github/workflows/build.yml"
    tags-ignore: [ "**" ]

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v4.0.0
        with:
          distribution: "temurin"
          java-version: 25

      - name: Mark executable
        run: chmod +x ./gradlew

      - name: Build
        uses: burrunan/gradle-cache-action@v3
        with:
          arguments: build
